# Config for a simple 256 -> 16 autoencoder
model:
  model_id: dcae
  sample_size: 256
  channels: 3
  latent_size: 4
  latent_channels: 256

  ch_0: 64
  ch_max: 256

  encoder_blocks_per_stage: [1, 1, 1, 1, 1, 1, 1]
  decoder_blocks_per_stage: [1, 1, 1, 1, 1, 1, 1]
  discriminator_blocks_per_stage: []

  checkpoint_grads: true

train:
  trainer_id: cyclegan
  data_id_A: local_cod
  data_kwargs_A:
    root: ../cod_data/raw

  data_id_B: local_cod
  data_kwargs_B:
    root: ../hla

  target_batch_size: 4
  batch_size: 4

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 2.0e-4
    betas: [0.5, 0.999]
    weight_decay: 1.0e-4
    eps: 1.0e-15

  checkpoint_dir: checkpoints/v0
  resume_ckpt: null

  sample_interval: 1000
  save_interval: 5000

  loss_weights:
    r1: 0.0
    r2: 0.0
    cycle: 10.0

wandb:
  name: ${env:WANDB_USER_NAME}
  project: cycle_gan
  run_name: v0
